# Data Cleaning Notebook
Week 4 IDX Exchange


Jack Phelan

# Setup

In [5]:
#imports
import pandas as pd

In [6]:
# read in data
enriched_listings = pd.read_csv("./../data/enriched/listings_with_rates.csv", low_memory=False)
enriched_sold = pd.read_csv("./../data/enriched/sold_with_rates.csv", low_memory=False)

In [8]:
def dt_converter(df): 
    # Convert date fields to datetime format
    date_fields = ['CloseDate', 'PurchaseContractDate', 'ListingContractDate', 'ContractStatusChangeDate']
    for field in date_fields:
        if field in df.columns:
            df[field] = pd.to_datetime(df[field], errors='coerce')
    return df

In [7]:
enriched_listings.head(5)

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,BuyerAgencyCompensationType,BuyerAgencyCompensation,year_month
0,929000.0,1076194146,dianne@drector.com,NaN,NaN,Dianne,Rector,NaN,NaN,16882 Canyon Lane,...,Huntington Beach Union High,92649,NaN,330.0,1847.0,NaN,16882 Canyon Lane,NaN,NaN,2024-05
1,999999.0,1076194026,realestateby_denisegarcia@gmail.com,NaN,NaN,Denise,Garcia,NaN,NaN,8720 S 4th Avenue,...,Inglewood Unified,90305,NaN,0.0,8508.0,NaN,8720 S 4th Avenue,NaN,NaN,2024-05
2,1400000.0,1076193814,alizabethjames@hotmail.com,NaN,NaN,Alizabeth,James,33.858559,-116.542169,505 E Molino Road,...,Palm Springs Unified,92262,NaN,NaN,10890.0,NaN,505 E Molino Road,NaN,NaN,2024-05
3,4998888.0,1076193812,ernieramos62@yahoo.com,NaN,NaN,Ernesto,Ramos,NaN,NaN,3653 Halldale Avenue,...,NaN,90018,NaN,NaN,6192.0,NaN,3653 Halldale Avenue,NaN,NaN,2024-05
4,549000.0,1076193525,parsanina@yahoo.com,NaN,NaN,Nina,Parsa,NaN,NaN,1736 N Mcdivitt Avenue,...,Los Angeles Unified,90221,NaN,0.0,4113.0,NaN,1736 N Mcdivitt Avenue,NaN,NaN,2024-05

## Task List
- Convert date fields to datetime format (CloseDate, PurchaseContractDate, ListingContractDate, ContractStatusChangeDate)
- Remove unnecessary or redundant columns
- Handle missing values appropriately
- Ensure numeric fields are properly typed
- Remove or flag invalid numeric values: ClosePrice <= 0, LivingArea <= 0, DaysOnMarket < 0,
negative Bedrooms or Bathrooms

In [9]:
int_list = dt_converter(enriched_listings)

In [11]:
dt_cols = ['CloseDate', 'PurchaseContractDate', 'ListingContractDate', 'ContractStatusChangeDate']
int_list[dt_cols].head(5)

  CloseDate PurchaseContractDate ListingContractDate ContractStatusChangeDate
0       NaT                  NaT          2024-05-10               2024-05-10
1       NaT                  NaT          2024-05-30               2024-05-30
2       NaT                  NaT          2024-05-21               2024-05-21
3       NaT                  NaT          2024-05-29               2024-05-29
4       NaT                  NaT          2024-05-27               2024-05-27

In [ ]:
int_list