# **EDA Notebook**
IDX Exchange Weeks 2-3 Assignment 

by Jack Phelan : )

In [8]:
#importd
import pandas as pd

In [9]:
# loading data from concat-ed csv
listings_df_raw = pd.read_csv("../data/outputs/listings.csv")
sold_df_raw = pd.read_csv("../data/outputs/sold.csv")

/var/folders/9w/27dwnd7s3plbp9xj1v9qrn5m0000gn/T/ipykernel_31810/2448680216.py:2: DtypeWarning: Columns (0: BuyerOfficeName, 1: BuyerAgentMlsId, 2: BuyerAgentFirstName, 3: BuyerAgentLastName, 4: BuyerOfficeAOR, 5: CoBuyerAgentFirstName, 6: FireplaceYN, 7: LotSizeDimensions, 8: PostalCode, 9: BuyerOfficeName.1, 10: BuyerAgencyCompensationType) have mixed types. Specify dtype option on import or set low_memory=False.
  listings_df_raw = pd.read_csv("../data/outputs/listings.csv")
/var/folders/9w/27dwnd7s3plbp9xj1v9qrn5m0000gn/T/ipykernel_31810/2448680216.py:3: DtypeWarning: Columns (0: BuyerAgencyCompensationType, 1: latfilled, 2: lonfilled, 3: BuyerAgentAOR, 4: ListAgentAOR, 5: OriginatingSystemName, 6: OriginatingSystemSubName) have mixed types. Specify dtype option on import or set low_memory=False.
  sold_df_raw = pd.read_csv("../data/outputs/sold.csv")

In [10]:
# previews
listings_df_raw.head(5)

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,BuyerAgencyCompensationType,BuyerAgencyCompensation
0,929000.0,1076194146,dianne@drector.com,NaN,NaN,Dianne,Rector,NaN,NaN,16882 Canyon Lane,...,2.0,Huntington Beach Union High,92649,NaN,330.0,1847.0,NaN,16882 Canyon Lane,NaN,NaN
1,999999.0,1076194026,realestateby_denisegarcia@gmail.com,NaN,NaN,Denise,Garcia,NaN,NaN,8720 S 4th Avenue,...,2.0,Inglewood Unified,90305,NaN,0.0,8508.0,NaN,8720 S 4th Avenue,NaN,NaN
2,1400000.0,1076193814,alizabethjames@hotmail.com,NaN,NaN,Alizabeth,James,33.858559,-116.542169,505 E Molino Road,...,2.0,Palm Springs Unified,92262,NaN,NaN,10890.0,NaN,505 E Molino Road,NaN,NaN
3,549000.0,1076193525,parsanina@yahoo.com,NaN,NaN,Nina,Parsa,NaN,NaN,1736 N Mcdivitt Avenue,...,2.0,Los Angeles Unified,90221,NaN,0.0,4113.0,NaN,1736 N Mcdivitt Avenue,NaN,NaN
4,729999.0,1076193391,tony.labellarte@gmail.com,NaN,NaN,Antonio,Labellarte,NaN,NaN,13130 Mercer Street,...,0.0,Los Angeles Unified,91331,NaN,0.0,3551.0,NaN,13130 Mercer Street,NaN,NaN

In [11]:
sold_df_raw.head(5)

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled,BuyerAgentAOR,ListAgentAOR,OriginatingSystemName,OriginatingSystemSubName
0,NaN,True,NaN,NaN,False,265000.0,543251400,michaelg@londonproperties.com,2024-04-02,250000.0,...,93726,0.0,8100.0,NaN,False,False,NaN,NaN,NaN,NaN
1,NaN,True,NaN,NaN,False,429000.0,519252621,robynsong@aol.com,2024-04-30,413700.0,...,92561,0.0,43560.0,NaN,False,False,NaN,NaN,NaN,NaN
2,NaN,True,NaN,NaN,False,600000.0,492708527,maryvillamarhomes@gmail.com,2024-04-03,725000.0,...,92173,0.0,10557.0,NaN,False,False,NaN,NaN,NaN,NaN
3,NaN,False,NaN,NaN,False,600000.0,1073316150,jeff@whittingtonre.com,2024-04-12,600000.0,...,91977,NaN,8130.0,NaN,True,True,NaN,NaN,NaN,NaN
4,Carpet,NaN,NaN,NaN,False,575000.0,1073312736,erin@mckeonhomes.com,2024-04-08,600000.0,...,94134,154.0,1424.0,NaN,True,True,NaN,NaN,NaN,NaN

# **Listings Analysis**

## **Dataset Overview**

In [ ]:
# basic info about data
print("Listings DataFrame Info:")
print(listings_df_raw.shape[0], "rows,", listings_df_raw.shape[1], "columns")
print("Number of float columns:", len(listings_df_raw.select_dtypes(include=['float64']).columns.tolist()))
print("Number of int columns:", len(listings_df_raw.select_dtypes(include=['int64']).columns.tolist()))
print("Number of object columns:", len(listings_df_raw.select_dtypes(include=['object']).columns.tolist()))
print("Number of string columns:", len(listings_df_raw.select_dtypes(include=['string']).columns.tolist()))

Listings DataFrame Info:
426011 rows, 84 columns
Number of float columns: 33
Number of int columns: 4
Number of object columns: 47
Number of string columns: 43

/var/folders/9w/27dwnd7s3plbp9xj1v9qrn5m0000gn/T/ipykernel_31810/399217943.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print("Number of object columns:", len(listings_df_raw.select_dtypes(include=['object']).columns.tolist()))

In [ ]:
# specific dtypes 
display(listings_df_raw.dtypes)

OriginalListPrice               float64
ListingKey                        int64
ListAgentEmail                      str
CloseDate                           str
ClosePrice                      float64
                                 ...
LotSizeSquareFeet               float64
MiddleOrJuniorSchoolDistrict    float64
UnparsedAddress.1                   str
BuyerAgencyCompensationType         str
BuyerAgencyCompensation         float64
Length: 84, dtype: object

In [12]:
listings_df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 426011 entries, 0 to 426010
Data columns (total 84 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             425380 non-null  float64
 1   ListingKey                    426011 non-null  int64
 2   ListAgentEmail                424966 non-null  str
 3   CloseDate                     125173 non-null  str
 4   ClosePrice                    109002 non-null  float64
 5   ListAgentFirstName            422667 non-null  str
 6   ListAgentLastName             425986 non-null  str
 7   Latitude                      351296 non-null  float64
 8   Longitude                     351296 non-null  float64
 9   UnparsedAddress               425403 non-null  str
 10  PropertyType                  426011 non-null  str
 11  LivingArea                    425581 non-null  float64
 12  ListPrice                     426011 non-null  float64
 13  DaysOnMarket                  426011 non-null  int64
 14  ListOfficeName                426011 non-null  str
 15  BuyerOfficeName               118195 non-null  str
 16  CoListOfficeName              95340 non-null   str
 17  ListAgentFullName             425943 non-null  str
 18  CoListAgentFirstName          94908 non-null   str
 19  CoListAgentLastName           95226 non-null   str
 20  BuyerAgentMlsId               119862 non-null  str
 21  BuyerAgentFirstName           119350 non-null  str
 22  BuyerAgentLastName            119944 non-null  str
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       182448 non-null  str
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             426011 non-null  int64
 27  MLSAreaMajor                  368883 non-null  str
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                426011 non-null  str
 30  PropertyType.1                426011 non-null  str
 31  MlsStatus                     426011 non-null  str
 32  ElementarySchool              50989 non-null   str
 33  ListAgentFirstName.1          422667 non-null  str
 34  AttachedGarageYN              351833 non-null  object
 35  ParkingTotal                  425992 non-null  float64
 36  BuilderName                   19716 non-null   str
 37  PropertySubType               425092 non-null  str
 38  LotSizeAcres                  390959 non-null  float64
 39  SubdivisionName               156487 non-null  str
 40  BuyerOfficeAOR                111153 non-null  str
 41  YearBuilt                     425344 non-null  float64
 42  DaysOnMarket.1                426011 non-null  int64
 43  StreetNumberNumeric           425258 non-null  float64
 44  LivingArea.1                  425581 non-null  float64
 45  ListingId                     426011 non-null  str
 46  BathroomsTotalInteger         425965 non-null  float64
 47  City                          425589 non-null  str
 48  TaxYear                       0 non-null       float64
 49  BuildingAreaTotal             37357 non-null   float64
 50  BedroomsTotal                 425894 non-null  float64
 51  ContractStatusChangeDate      420996 non-null  str
 52  Longitude.1                   351296 non-null  float64
 53  ElementarySchoolDistrict      0 non-null       float64
 54  CoBuyerAgentFirstName         10885 non-null   str
 55  PurchaseContractDate          208050 non-null  str
 56  ListingContractDate           426011 non-null  str
 57  BelowGradeFinishedArea        2402 non-null    float64
 58  BusinessType                  0 non-null       float64
 59  Latitude.1                    351296 non-null  float64
 60  ListPrice.1                   426011 non-null  float64
 61  StateOrProvince               425973 non-null  str
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          51062 non-null   str
 64  FireplaceYN                   425564 non-null  object
 65  Stories                       351387 non-null  float64
 66  HighSchool                    66934 non-null   str
 67  Levels                        379686 non-null  str
 68  ListAgentLastName.1           425986 non-null  str
 69  CloseDate.1                   125173 non-null  str
 70  LotSizeDimensions             22041 non-null   str
 71  LotSizeArea                   391630 non-null  float64
 72  MainLevelBedrooms             232650 non-null  float64
 73  NewConstructionYN             396715 non-null  object
 74  GarageSpaces                  402649 non-null  float64
 75  HighSchoolDistrict            298980 non-null  str
 76  PostalCode                    426004 non-null  object
 77  BuyerOfficeName.1             118195 non-null  str
 78  AssociationFee                324228 non-null  float64
 79  LotSizeSquareFeet             391507 non-null  float64
 80  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 81  UnparsedAddress.1             425403 non-null  str
 82  BuyerAgencyCompensationType   79013 non-null   str
 83  BuyerAgencyCompensation       78993 non-null   float64
dtypes: float64(33), int64(4), object(4), str(43)
memory usage: 273.0+ MB

In [26]:
listings_df_raw.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,BuyerAgencyCompensationType,BuyerAgencyCompensation
0,929000.0,1076194146,dianne@drector.com,NaN,NaN,Dianne,Rector,NaN,NaN,16882 Canyon Lane,...,2.0,Huntington Beach Union High,92649,NaN,330.0,1847.0,NaN,16882 Canyon Lane,NaN,NaN
1,999999.0,1076194026,realestateby_denisegarcia@gmail.com,NaN,NaN,Denise,Garcia,NaN,NaN,8720 S 4th Avenue,...,2.0,Inglewood Unified,90305,NaN,0.0,8508.0,NaN,8720 S 4th Avenue,NaN,NaN
2,1400000.0,1076193814,alizabethjames@hotmail.com,NaN,NaN,Alizabeth,James,33.858559,-116.542169,505 E Molino Road,...,2.0,Palm Springs Unified,92262,NaN,NaN,10890.0,NaN,505 E Molino Road,NaN,NaN
3,549000.0,1076193525,parsanina@yahoo.com,NaN,NaN,Nina,Parsa,NaN,NaN,1736 N Mcdivitt Avenue,...,2.0,Los Angeles Unified,90221,NaN,0.0,4113.0,NaN,1736 N Mcdivitt Avenue,NaN,NaN
4,729999.0,1076193391,tony.labellarte@gmail.com,NaN,NaN,Antonio,Labellarte,NaN,NaN,13130 Mercer Street,...,0.0,Los Angeles Unified,91331,NaN,0.0,3551.0,NaN,13130 Mercer Street,NaN,NaN

In [ ]:
METADATA_COLS = [
'ListingKey',
'ListAgentEmail',
'ListAgentFirstName',
'ListAgentLastName',
'ListOfficeName',
'BuyerOfficeName',
'CoListOfficeName',
'ListAgentFullName',
'CoListAgentFirstName',
'CoListAgentLastName',
'BuyerAgentMlsId',
'BuyerAgentFirstName',
'BuyerAgentLastName',
'ListingKeyNumeric',
'ListAgentFirstName.1',
'BuilderName',
'SubdivisionName',
'BuyerOfficeAOR',
'DaysOnMarket.1',
'LivingArea.1',
'ListingId',
'CoBuyerAgentFirstName',
'ListAgentLastName.1',
'CloseDate.1'
]

## **Missingness Assessment**

## **Numeric Distribution Analysis**