# Feature Engineering Notebook

# Setup

In [2]:
#imports
import pandas as pd

In [3]:
df_l = pd.read_csv(".././data/cleaned/cleaned_listings.csv", low_memory=False)
df_s = pd.read_csv(".././data/cleaned/cleaned_sold.csv", low_memory=False)

# Engineering

In [4]:
# fe helper functions
def make_price_ratio(df): 
    df = df.copy()
    df['price_ratio'] = df['ClosePrice'] / df['OriginalListPrice']
    return df

def make_price_per_sqft(df): 
    df = df.copy()
    df['price_per_sqft'] = df['ClosePrice'] / df['LivingArea']
    return df

def make_days_on_market(df):
    df = df.copy()
    df['days_on_market'] = (pd.to_datetime(df['CloseDate']) - pd.to_datetime(df['ListingContractDate'])).dt.days
    return df

def make_yr_month(df):
    df = df.copy()
    df['yr_month'] = pd.to_datetime(df['CloseDate']).dt.to_period('M')
    return df

def make_listing_to_contract_days(df):
    df = df.copy()
    df['listing_to_contract_days'] = (pd.to_datetime(df['PurchaseContractDate']) - pd.to_datetime(df['ListingContractDate'])).dt.days
    return df

def make_contract_to_close_days(df):
    df = df.copy()
    df['contract_to_close_days'] = (pd.to_datetime(df['CloseDate']) - pd.to_datetime(df['PurchaseContractDate'])).dt.days
    return df

In [5]:
# call func for all
def feature_engineering(df):
    # Example feature engineering steps
    df = make_price_ratio(df)
    df = make_price_per_sqft(df)
    df = make_days_on_market(df)
    df = make_yr_month(df)
    df = make_listing_to_contract_days(df)
    df = make_contract_to_close_days(df)

    return df

In [6]:
df_l.head(5)

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,...,BuyerAgencyCompensation,year_month,impossible_measurement_flag,impossible_year_flag,listing_after_close_flag,purchase_after_close_flag,negative_timeline_flag,null_coords_flag,placeholder_coords_flag,non_cali_coords_flag
0,929000.0,1076194146,NaN,NaN,NaN,NaN,16882 Canyon Lane,Residential,1389.0,929000.0,...,NaN,2024-05,False,False,False,False,False,True,False,False
1,999999.0,1076194026,NaN,NaN,NaN,NaN,8720 S 4th Avenue,Residential,2526.0,999999.0,...,NaN,2024-05,False,False,False,False,False,True,False,False
2,1400000.0,1076193814,NaN,NaN,33.858559,-116.542169,505 E Molino Road,Residential,2256.0,1400000.0,...,NaN,2024-05,False,False,False,False,False,False,False,True
3,4998888.0,1076193812,NaN,NaN,NaN,NaN,3653 Halldale Avenue,ResidentialIncome,NaN,4998888.0,...,NaN,2024-05,False,False,False,False,False,True,False,False
4,549000.0,1076193525,NaN,NaN,NaN,NaN,1736 N Mcdivitt Avenue,Residential,986.0,549000.0,...,NaN,2024-05,False,False,False,False,False,True,False,False

In [7]:
df_le = feature_engineering(df_l)
df_ls = feature_engineering(df_s)

# Pipeline Testing

In [ ]:
from idx.components import ingest, preprocessing, feature_engineering, cleaning
from sklearn.pipeline import Pipeline
import geopandas as gpd

district_gdf = gpd.read_file("../data/raw/district/DistrictAreas2425.shp")
district_gdf = district_gdf.to_crs(epsg=4326)




ingestor = ingest.MLSIngestor(input_path="../data/raw/")
fred_ingestor = ingest.FredMerger()
cleaner = preprocessing.DataCleaner()
flagger = preprocessing.BadDataFlagger()
market_maker = feature_engineering.CreateMarketMetrics()
cleanup = feature_engineering.CleanUpTransformer()
null = feature_engineering.NullDropper()
dist_merger = feature_engineering.DistrictMerger(district_gdf=district_gdf)
iqr_flagger = cleaning.OutlierFlagger(subset=["OriginalListPrice", "LivingArea", "LotSizeArea"])

ingest_test = Pipeline([ 
    ("ingestor", ingestor),
    ("fred_ingestor", fred_ingestor),
    ("cleaner", cleaner),
    ("flagger", flagger),
    ("market_maker", market_maker),
    ("cleanup", cleanup),
    ("null", null),
    ("dist_merger", dist_merger),
    ("iqr_flagger", iqr_flagger)
])


df_sold, df_listings = ingest_test.fit_transform(X=None, y=None)
# rest of notebook wont work oops be careful
df_listings_districts = df_listings.copy()

In [9]:
# TODO : add school districts; add outlier detection/dropping to data cleaning
# TODO : make componenets. add imputation and train/test split perchance

In [10]:
"""# Adding school district stuff

district_gdf = gpd.read_file("../data/raw/district/DistrictAreas2425.shp")

district_gdf = district_gdf.to_crs(epsg=4326)

df_listings['geometry'] = df_listings.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)

df_listings_gdf = gpd.GeoDataFrame(df_listings, geometry='geometry', crs="EPSG:4326")

df_listings_with_districts = gpd.sjoin(df_listings_gdf, district_gdf, how="left", predicate='within')"""

'# Adding school district stuff\n\ndistrict_gdf = gpd.read_file("../data/raw/district/DistrictAreas2425.shp")\n\ndistrict_gdf = district_gdf.to_crs(epsg=4326)\n\ndf_listings[\'geometry\'] = df_listings.apply(lambda row: Point(row[\'Longitude\'], row[\'Latitude\']), axis=1)\n\ndf_listings_gdf = gpd.GeoDataFrame(df_listings, geometry=\'geometry\', crs="EPSG:4326")\n\ndf_listings_with_districts = gpd.sjoin(df_listings_gdf, district_gdf, how="left", predicate=\'within\')'

In [11]:

import geopandas as gpd
from shapely.geometry import Point
def geo_merge(df, gdf, lon_col='Longitude', lat_col='Latitude', district_col='DISTRICT'):
    """
    Merges a DataFrame with a GeoDataFrame based on geographic coordinates.

    Parameters:
    df (pd.DataFrame): The DataFrame containing the data to merge.
    gdf (gpd.GeoDataFrame): The GeoDataFrame containing the geographic data.
    lon_col (str): The name of the longitude column in df.
    lat_col (str): The name of the latitude column in df.
    district_col (str): The name of the district column in gdf.

    Returns:
    pd.DataFrame: A DataFrame with the merged data, including the district information.
    """
    
    # Create a GeoDataFrame from the input DataFrame
    df['geometry'] = df.apply(lambda row: Point(row[lon_col], row[lat_col]), axis=1)
    df_gdf = gpd.GeoDataFrame(df, geometry='geometry', crs="EPSG:4326")
    
    # Perform spatial join
    merged_gdf = gpd.sjoin(df_gdf, gdf[[district_col, 'geometry']], how="left", predicate='within')
    
    # Drop the geometry column and return as a regular DataFrame
    merged_df = merged_gdf.drop(columns=['geometry'])
    
    return merged_df

In [12]:
"""df_listings_districts = geo_merge(df_listings, district_gdf, lon_col='Longitude', lat_col='Latitude', district_col='DistrictNa')
df_listings_districts.head(5)"""

"df_listings_districts = geo_merge(df_listings, district_gdf, lon_col='Longitude', lat_col='Latitude', district_col='DistrictNa')\ndf_listings_districts.head(5)"

# Segment Analysis

Generate summary statistics for each segment:
- PropertyType and PropertySubType
- CountyOrParish and MLSAreaMajor
- ListOfficeName and BuyerOfficeName (for competitive intelligence)

In [13]:
df_listings_districts.groupby(["PropertyType", "PropertySubType"]).agg(
    {"ClosePrice": ["mean", "median"], "price_per_sqft": ["mean", "median"]}
)

                                      ClosePrice         price_per_sqft  \
                                            mean  median           mean
PropertyType     PropertySubType
CommercialLease  Agriculture         2800.000000  2800.0            NaN
                 Business          330970.033659  1850.0            NaN
                 Industrial         22216.783333  3325.0            NaN
                 MixedUse            2619.979167  2131.0            NaN
                 MultiFamily          208.333333   200.0            NaN
...                                          ...     ...            ...
ResidentialLease StockCooperative    4828.946078  2650.0       4.587285
                 Studio              1901.899628  1750.0            inf
                 Timeshare           3500.000000  3500.0       1.959686
                 Townhouse           8550.438680  3800.0            inf
                 Triplex             2861.338428  2662.5       3.322981


                                     median
PropertyType     PropertySubType
CommercialLease  Agriculture            NaN
                 Business               NaN
                 Industrial             NaN
                 MixedUse               NaN
                 MultiFamily            NaN
...                                     ...
ResidentialLease StockCooperative  2.716032
                 Studio            4.166667
                 Timeshare         1.959686
                 Townhouse         2.621274
                 Triplex           3.118737

[75 rows x 4 columns]

In [14]:
df_listings_districts.groupby(["CountyOrParish", "MLSAreaMajor"]).agg(
    {"ClosePrice": ["mean", "median"], "price_per_sqft": ["mean", "median"]}
)

                                        ClosePrice            price_per_sqft  \
                                              mean     median           mean
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined      1.137391e+06  1005000.0     659.430117
               BERK - Berkeley        7.667500e+04    76675.0     182.564622
Amador         699 - Not Defined      1.840000e+05   184000.0     136.904762
Butte          699 - Not Defined      2.261671e+05   239000.0     184.625141
               PARA - Paradise        2.072194e+05    47500.0     255.572259
...                                            ...        ...            ...
Ventura        VTU - Ventura          5.884756e+05   655000.0     445.916984
               WEH - West Hills       3.599500e+05     3150.0     128.802886
               WV - Westlake Village  9.888756e+05   567000.0     351.382198
Yolo           699 - Not Defined      4.044500e+05   375000.0     241.409408
Yuba           699 - Not Defined      4.126667e+05   435000.0     281.323332


                                          median
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined      666.360294
               BERK - Berkeley        182.564622
Amador         699 - Not Defined      136.904762
Butte          699 - Not Defined      182.796053
               PARA - Paradise        267.214800
...                                          ...
Ventura        VTU - Ventura          479.400147
               WEH - West Hills         3.400000
               WV - Westlake Village  451.576191
Yolo           699 - Not Defined      274.633154
Yuba           699 - Not Defined      288.844622

[1207 rows x 4 columns]

In [15]:
df_listings_districts.groupby('ListOfficeName').agg(
    {"ClosePrice": ["mean", "median"], "price_per_sqft": ["mean", "median"]}
)

                                  ClosePrice            price_per_sqft  \
                                        mean     median           mean
ListOfficeName
#1 FLAT FEE-LIBERTY REALTY      9.450000e+05   945000.0     507.791510
*                               3.500000e+03     3500.0       2.623688
1 Percent Lists Desert 2 Coast  3.500000e+03     3500.0       2.128954
1 Percent Lists SoCal           3.318871e+05     4500.0     271.520997
1 Realty                        1.368000e+05   220000.0     102.121953
...                                      ...        ...            ...
rjestate inc.                   7.110000e+05   711000.0     469.616909
smithREgroup                    5.150667e+05     3850.0       3.021182
socalhomeshop Inc.              3.550000e+03     2850.0       2.797368
ten21 Properties                8.070000e+05   807000.0     959.571938
zRE Group                       5.162500e+06  5162500.0    1892.081471


                                     median
ListOfficeName
#1 FLAT FEE-LIBERTY REALTY       507.791510
*                                  2.623688
1 Percent Lists Desert 2 Coast     2.128954
1 Percent Lists SoCal              3.294798
1 Realty                         158.045977
...                                     ...
rjestate inc.                    469.616909
smithREgroup                       3.217391
socalhomeshop Inc.                 2.842105
ten21 Properties                 959.571938
zRE Group                       1892.081471

[14816 rows x 4 columns]

In [16]:
df_listings_districts.groupby('BuyerOfficeName').agg(
    {"ClosePrice": ["mean", "median"], "price_per_sqft": ["mean", "median"]}
)

                                  ClosePrice            price_per_sqft  \
                                        mean     median           mean
BuyerOfficeName
& Company Real Estate           3.500000e+03     3500.0       2.916667
*                               5.328333e+05   730000.0     432.062794
, Inc                           2.225000e+06  2225000.0    1115.288221
1                               8.950000e+05   895000.0     497.222222
1 Percent Lists Desert 2 Coast  3.500000e+03     3500.0       2.128954
...                                      ...        ...            ...
uDream Real Estate              1.052500e+06  1052500.0     869.834711
windermere signature            6.100000e+05   610000.0            NaN
yesenia@myaxisrealestate.com    4.150000e+05   415000.0     268.782383
zDefault Office                 4.150000e+03     4500.0       2.348074
zRE Group                       1.006000e+06  1027500.0     502.368766


                                     median
BuyerOfficeName
& Company Real Estate              2.916667
*                                599.343186
, Inc                           1115.288221
1                                497.222222
1 Percent Lists Desert 2 Coast     2.128954
...                                     ...
uDream Real Estate               869.834711
windermere signature                    NaN
yesenia@myaxisrealestate.com     268.782383
zDefault Office                    2.161383
zRE Group                        562.595033

[15661 rows x 4 columns]

# Export

In [17]:
"""df_sold_districts = geo_merge(df_sold, district_gdf, lon_col='Longitude', lat_col='Latitude', district_col='DistrictNa')"""

"df_sold_districts = geo_merge(df_sold, district_gdf, lon_col='Longitude', lat_col='Latitude', district_col='DistrictNa')"

In [18]:
"""df_sold_districts.to_csv("../data/enriched/geo_enhanced_sold_data.csv", index=False)
df_listings_districts.to_csv("../data/enriched/geo_enhanced_listings_data.csv", index=False)"""

'df_sold_districts.to_csv("../data/enriched/geo_enhanced_sold_data.csv", index=False)\ndf_listings_districts.to_csv("../data/enriched/geo_enhanced_listings_data.csv", index=False)'