# Feature Engineering Notebook

# Setup

In [1]:
#imports
import pandas as pd

In [2]:
df_l = pd.read_csv(".././data/cleaned/cleaned_listings.csv", low_memory=False)
df_s = pd.read_csv(".././data/cleaned/cleaned_sold.csv", low_memory=False)

# Engineering

In [3]:
# fe helper functions
def make_price_ratio(df): 
    df = df.copy()
    df['price_ratio'] = df['ClosePrice'] / df['OriginalListPrice']
    return df

def make_price_per_sqft(df): 
    df = df.copy()
    df['price_per_sqft'] = df['ClosePrice'] / df['LivingArea']
    return df

def make_days_on_market(df):
    df = df.copy()
    df['days_on_market'] = (pd.to_datetime(df['CloseDate']) - pd.to_datetime(df['ListingContractDate'])).dt.days
    return df

def make_yr_month(df):
    df = df.copy()
    df['yr_month'] = pd.to_datetime(df['CloseDate']).dt.to_period('M')
    return df

def make_listing_to_contract_days(df):
    df = df.copy()
    df['listing_to_contract_days'] = (pd.to_datetime(df['PurchaseContractDate']) - pd.to_datetime(df['ListingContractDate'])).dt.days
    return df

def make_contract_to_close_days(df):
    df = df.copy()
    df['contract_to_close_days'] = (pd.to_datetime(df['CloseDate']) - pd.to_datetime(df['PurchaseContractDate'])).dt.days
    return df

In [4]:
# call func for all
def feature_engineering(df):
    # Example feature engineering steps
    df = make_price_ratio(df)
    df = make_price_per_sqft(df)
    df = make_days_on_market(df)
    df = make_yr_month(df)
    df = make_listing_to_contract_days(df)
    df = make_contract_to_close_days(df)

    return df

In [5]:
df_l.head(5)

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,...,BuyerAgencyCompensation,year_month,impossible_measurement_flag,impossible_year_flag,listing_after_close_flag,purchase_after_close_flag,negative_timeline_flag,null_coords_flag,placeholder_coords_flag,non_cali_coords_flag
0,929000.0,1076194146,NaN,NaN,NaN,NaN,16882 Canyon Lane,Residential,1389.0,929000.0,...,NaN,2024-05,False,False,False,False,False,True,False,False
1,999999.0,1076194026,NaN,NaN,NaN,NaN,8720 S 4th Avenue,Residential,2526.0,999999.0,...,NaN,2024-05,False,False,False,False,False,True,False,False
2,1400000.0,1076193814,NaN,NaN,33.858559,-116.542169,505 E Molino Road,Residential,2256.0,1400000.0,...,NaN,2024-05,False,False,False,False,False,False,False,True
3,4998888.0,1076193812,NaN,NaN,NaN,NaN,3653 Halldale Avenue,ResidentialIncome,NaN,4998888.0,...,NaN,2024-05,False,False,False,False,False,True,False,False
4,549000.0,1076193525,NaN,NaN,NaN,NaN,1736 N Mcdivitt Avenue,Residential,986.0,549000.0,...,NaN,2024-05,False,False,False,False,False,True,False,False

In [6]:
df_le = feature_engineering(df_l)
df_ls = feature_engineering(df_s)

# Pipeline Testing

In [7]:
from idx.components import ingest, preprocessing, feature_engineering
from sklearn.pipeline import Pipeline


ingestor = ingest.MLSIngestor(input_path="../data/raw/")
fred_ingestor = ingest.FredMerger()
cleaner = preprocessing.DataCleaner()
flagger = preprocessing.BadDataFlagger()
market_maker = feature_engineering.CreateMarketMetrics()

ingest_test = Pipeline([ 
    ("ingestor", ingestor),
    ("fred_ingestor", fred_ingestor),
    ("cleaner", cleaner),
    ("flagger", flagger),
    ("market_maker", market_maker)
])


df_sold, df_listings = ingest_test.fit_transform(X=None, y=None)

In [8]:
# TODO : add school districts; add outlier detection/dropping to data cleaning
# TODO : make componenets. add imputation and train/test split perchance

In [14]:
# Adding school district stuff
import geopandas as gpd
from shapely.geometry import Point

district_gdf = gpd.read_file("../data/raw/district/DistrictAreas2425.shp")

district_gdf = district_gdf.to_crs(epsg=4326)

df_listings['geometry'] = df_listings.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)

df_listings_gdf = gpd.GeoDataFrame(df_listings, geometry='geometry', crs="EPSG:4326")

df_listings_with_districts = gpd.sjoin(df_listings_gdf, district_gdf, how="left", predicate='within')

In [16]:
def geo_merge(df, gdf, lon_col='Longitude', lat_col='Latitude', district_col='DISTRICT'):
    """
    Merges a DataFrame with a GeoDataFrame based on geographic coordinates.

    Parameters:
    df (pd.DataFrame): The DataFrame containing the data to merge.
    gdf (gpd.GeoDataFrame): The GeoDataFrame containing the geographic data.
    lon_col (str): The name of the longitude column in df.
    lat_col (str): The name of the latitude column in df.
    district_col (str): The name of the district column in gdf.

    Returns:
    pd.DataFrame: A DataFrame with the merged data, including the district information.
    """
    
    # Create a GeoDataFrame from the input DataFrame
    df['geometry'] = df.apply(lambda row: Point(row[lon_col], row[lat_col]), axis=1)
    df_gdf = gpd.GeoDataFrame(df, geometry='geometry', crs="EPSG:4326")
    
    # Perform spatial join
    merged_gdf = gpd.sjoin(df_gdf, gdf[[district_col, 'geometry']], how="left", predicate='within')
    
    # Drop the geometry column and return as a regular DataFrame
    merged_df = merged_gdf.drop(columns=['geometry'])
    
    return merged_df

In [18]:
df_listings_districts = geo_merge(df_listings, district_gdf, lon_col='Longitude', lat_col='Latitude', district_col='DistrictNa')
df_listings_districts.head(5)

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,...,placeholder_coords_flag,non_cali_coords_flag,price_ratio,price_per_sqft,days_on_market,yr_month,listing_to_contract_days,contract_to_close_days,index_right,DistrictNa
0,929000.0,1076194146,NaT,NaN,NaN,NaN,16882 Canyon Lane,Residential,1389.0,929000.0,...,False,False,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
1,999999.0,1076194026,NaT,NaN,NaN,NaN,8720 S 4th Avenue,Residential,2526.0,999999.0,...,False,False,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
2,1400000.0,1076193814,NaT,NaN,33.858559,-116.542169,505 E Molino Road,Residential,2256.0,1400000.0,...,False,True,NaN,NaN,NaN,NaT,NaN,NaN,478.0,Palm Springs Unified
3,4998888.0,1076193812,NaT,NaN,NaN,NaN,3653 Halldale Avenue,ResidentialIncome,NaN,4998888.0,...,False,False,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
4,549000.0,1076193525,NaT,NaN,NaN,NaN,1736 N Mcdivitt Avenue,Residential,986.0,549000.0,...,False,False,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN

# Segment Analysis

Generate summary statistics for each segment:
- PropertyType and PropertySubType
- CountyOrParish and MLSAreaMajor
- ListOfficeName and BuyerOfficeName (for competitive intelligence)

In [ ]:
df_listings_districts.groupby(["PropertyType", "PropertySubType"]).agg(
    {"ClosePrice": ["mean", "median"], "price_per_sqft": ["mean", "median"]}
)

                                         ClosePrice         price_per_sqft  \
                                               mean  median           mean
PropertyType        PropertySubType
BusinessOpportunity MixedUse                    NaN     NaN            NaN
CommercialLease     Agriculture         2800.000000  2800.0            NaN
                    Business          246734.337288  2000.0            NaN
                    Farm                        NaN     NaN            NaN
                    HotelMotel                  NaN     NaN            NaN
...                                             ...     ...            ...
ResidentialLease    StockCooperative    4773.708134  2600.0       4.540518
                    Studio              1908.595668  1750.0            inf
                    Timeshare           3500.000000  3500.0       1.959686
                    Townhouse           8202.907061  3800.0            inf
                    Triplex             2859.147644  2695.0       3.337170


                                        median
PropertyType        PropertySubType
BusinessOpportunity MixedUse               NaN
CommercialLease     Agriculture            NaN
                    Business               NaN
                    Farm                   NaN
                    HotelMotel             NaN
...                                        ...
ResidentialLease    StockCooperative  2.719298
                    Studio            4.184783
                    Timeshare         1.959686
                    Townhouse         2.622449
                    Triplex           3.125000

[89 rows x 4 columns]

In [22]:
df_listings_districts.groupby(["CountyOrParish", "MLSAreaMajor"]).agg(
    {"ClosePrice": ["mean", "median"], "price_per_sqft": ["mean", "median"]}
)

                                    ClosePrice            price_per_sqft  \
                                          mean     median           mean
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined  1.169423e+06  1095000.0     685.487433
               BERK - Berkeley    7.667500e+04    76675.0     182.564622
               GLV - Glenview              NaN        NaN            NaN
               VTU - Ventura               NaN        NaN            NaN
Alpine         699 - Not Defined           NaN        NaN            NaN
...                                        ...        ...            ...
Ventura        WW - Wagon Wheel            NaN        NaN            NaN
Yolo           699 - Not Defined  5.409714e+05   525000.0     319.109674
               LCOTH - Other               NaN        NaN            NaN
Yuba           699 - Not Defined  4.126667e+05   435000.0     281.323332
               LCOTH - Other               NaN        NaN            NaN


                                      median
CountyOrParish MLSAreaMajor
Alameda        699 - Not Defined  704.471243
               BERK - Berkeley    182.564622
               GLV - Glenview            NaN
               VTU - Ventura             NaN
Alpine         699 - Not Defined         NaN
...                                      ...
Ventura        WW - Wagon Wheel          NaN
Yolo           699 - Not Defined  372.429551
               LCOTH - Other             NaN
Yuba           699 - Not Defined  288.844622
               LCOTH - Other             NaN

[1507 rows x 4 columns]

In [23]:
df_listings_districts.groupby('ListOfficeName').agg(
    {"ClosePrice": ["mean", "median"], "price_per_sqft": ["mean", "median"]}
)

                           ClosePrice            price_per_sqft
                                 mean     median           mean       median
ListOfficeName
!RealAgent.com                    NaN        NaN            NaN          NaN
#1 FLAT FEE-LIBERTY REALTY   945000.0   945000.0     507.791510   507.791510
#1 Home Sales®                    NaN        NaN            NaN          NaN
#1 Realty Homes Inc.              NaN        NaN            NaN          NaN
*                              3500.0     3500.0       2.623688     2.623688
...                               ...        ...            ...          ...
socalhomeshop Inc.             3550.0     2850.0       2.797368     2.842105
ten21 Properties             807000.0   807000.0     959.571938   959.571938
uDream Real Estate                NaN        NaN            NaN          NaN
www.RonBishow.com                 NaN        NaN            NaN          NaN
zRE Group                   5162500.0  5162500.0    1892.081471  1892.081471

[24525 rows x 4 columns]

In [24]:
df_listings_districts.groupby('BuyerOfficeName').agg(
    {"ClosePrice": ["mean", "median"], "price_per_sqft": ["mean", "median"]}
)

                                  ClosePrice            price_per_sqft  \
                                        mean     median           mean
BuyerOfficeName
& Company Real Estate           3.500000e+03     3500.0       2.916667
*                               5.328333e+05   730000.0     432.062794
, Inc                           2.225000e+06  2225000.0    1115.288221
1                               8.950000e+05   895000.0     497.222222
1 Percent Lists Desert 2 Coast  3.500000e+03     3500.0       2.128954
...                                      ...        ...            ...
uDream Real Estate              1.052500e+06  1052500.0     869.834711
windermere signature            6.100000e+05   610000.0            NaN
yesenia@myaxisrealestate.com    4.150000e+05   415000.0     268.782383
zDefault Office                 4.150000e+03     4500.0       2.348074
zRE Group                       1.006000e+06  1027500.0     502.368766


                                     median
BuyerOfficeName
& Company Real Estate              2.916667
*                                599.343186
, Inc                           1115.288221
1                                497.222222
1 Percent Lists Desert 2 Coast     2.128954
...                                     ...
uDream Real Estate               869.834711
windermere signature                    NaN
yesenia@myaxisrealestate.com     268.782383
zDefault Office                    2.161383
zRE Group                        562.595033

[16975 rows x 4 columns]

# Export

In [25]:
df_sold_districts = geo_merge(df_sold, district_gdf, lon_col='Longitude', lat_col='Latitude', district_col='DistrictNa')

In [26]:
df_sold_districts.to_csv("../data/enriched/geo_enhanced_sold_data.csv", index=False)
df_listings_districts.to_csv("../data/enriched/geo_enhanced_listings_data.csv", index=False)